### ISSUE TITLE
set retry false

### ISSUE THREAD

**Issue by istvanfazakas** [spinx/sidekiq-job-php#3]
Hi,

I've tried setting retry to false, but it was not working.
Can you give me an example please? thanks!

**Comment by spinx** [comment]
Hey,

All jobs are set to retry by default. But you are right, there is a problem if you want to add a job that should not retry. Will fix it this weekend. Thanks for your help!

**Comment by spinx** [comment]
Fixed in the latest version. See https://github.com/spinx/sidekiq-job-php/blob/master/examples/basic.php for examples.
